spring.application.name=backend

# ?? ???? ???? dev? ??
spring.profiles.active=dev

# Security
jwt.secret=secretKeySecretKeySecretKeySecretKeySecretKeySecretKey

# CORS
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

# Server Port (Cloud Run)
server.port=${PORT:8080}