spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/ec_db?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=qwer1234

# ?? ??? ??? ??? ?? ???? update ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true